### PR TITLE
make it work

### PR DESCRIPTION
**Pull request by ralphtheninja**
Mega PR to make it work on latest master. Changes are:

* adding new class `LevelDOWNHyper` (converting from `LevelDOWN`)
* adding the hyperdex fork source to git
* adding `liveBackup()` to current `leveldown` code
* adjusting some tests
* renaming native target from `leveldown` to `leveldown-hyper` (`deps/leveldb/leveldb.gyp`)
* cleaning up `deps/leveldb/leveldb.gyp`

### CODE REVIEW

**Comment by juliangruber** [comment]
looks perfect to me, great work man!

**Comment by rvagg** [comment]
if it compiles and tests pass then :+1:

**Comment by rvagg** [comment]
and yeah, great work, you're a champion @ralphtheninja!

**Comment by ralphtheninja** [comment]
Thanks! :grinning: 

It compiles and tests pass on my machine. Would be great to get some feedback from other systems. Merging.

**Pull request merged**
