### PR TITLE
Bump Nan dep

### PR DESCRIPTION
**Pull request by 0x00A**

### CODE REVIEW

**Comment by 0x00A** [comment]
@ralphtheninja this seems to be failing because the package.json specifies an invalid version number?

**Comment by ralphtheninja** [comment]
This is related to prebuild, updated that here https://github.com/Level/leveldown-hyper/pull/20

**Comment by ralphtheninja** [comment]
@0x00A Mind rebasing this onto latest master?

**Comment by 0x00A** [comment]
@ralphtheninja can you publish to npm or add me to npm owners?

**Comment by ralphtheninja** [comment]
@0x00A I can do both ;)

**Comment by ralphtheninja** [comment]
@0x00A 1.1.1, prebuilt coming shortly

**Pull request merged**
