### PR TITLE
Fix native stuff

### PR DESCRIPTION
**Pull request by ralphtheninja**
Closes https://github.com/Level/leveldown-hyper/issues/36

Also fixes node 10

### CODE REVIEW

**Comment by ralphtheninja** [comment]
@peakji Will move over your fix on iterators from leveldown as well

**Comment by peakji** [comment]
BTW, HyperDex is [no longer maintained](https://github.com/rescrv/HyperDex/issues/233), and since then HyperLevelDB missed several important patches in the original LevelDB branch.

Shall we update HyperLevelDB from `1.0.2` to the latest (and final) [`1.2.2`](https://github.com/rescrv/HyperLevelDB/releases) version?

**Comment by ralphtheninja** [comment]
> Shall we update HyperLevelDB from 1.0.2 to the latest (and final) 1.2.2 version?

We can definitely do that. But I'd like to release a new major first based on latest `abstract-leveldown`.

**Comment by ralphtheninja** [comment]
@peakji Also, I've noticed that there are some stuff you made in leveldown that we perhaps should migrate over. Looking into that as well.

**Pull request merged**
