### PR TITLE
Nan 2.0 iojs 3.0 changes

### PR DESCRIPTION
**Pull request by ralphtheninja**
* updated with nan changes from leveldown
* patched iterator functionality with iterator.seek()
* updated LiveBackup code to work with latest nan changes

Compiles and tests work on linux x64

### CODE REVIEW

**Comment by ralphtheninja** [comment]
@mafintosh I'll add `prebuild` later once this goes through.

**Comment by rvagg** [comment]
that must have been quite a bit of work, lgtm if it works!

**Comment by ralphtheninja** [comment]
@rvagg Aye, I probably did it like 5 times to get it right :)

Could someone try this on OSX?

**Comment by maxogden** [comment]
all tests passed on yosemite w/ node.js 4.0.0 for me:

```
~/Desktop 🐈  git clone https://github.com/Level/leveldown-hyper.git
Cloning into 'leveldown-hyper'...
remote: Counting objects: 4176, done.
remote: Total 4176 (delta 0), reused 0 (delta 0), pack-reused 4176
Receiving objects: 100% (4176/4176), 11.13 MiB | 1.84 MiB/s, done.
Resolving deltas: 100% (2461/2461), done.
Checking connectivity... done.
~/Desktop 🐈  cd leveldown-hyper/
~/Desktop/leveldown-hyper 🐈  git fetch origin
~/Desktop/leveldown-hyper 🐈  git checkout -b nan-2.0-iojs-3.0 origin/nan-2.0-iojs-3.0
Branch nan-2.0-iojs-3.0 set up to track remote branch nan-2.0-iojs-3.0 from origin.
Switched to a new branch 'nan-2.0-iojs-3.0'
~/Desktop/leveldown-hyper 🐈  npm i
\
> leveldown-hyper@1.0.0 install /Users/max/Desktop/leveldown-hyper
> node-gyp rebuild

  CXX(target) Release/obj.target/leveldb-hyper/deps/leveldb/leveldb-hyper-1.0.2/util/bloom.o
  CXX(target) Release/obj.target/leveldb-hyper/deps/leveldb/leveldb-hyper-1.0.2/util/env_posix.o
  CXX(target) Release/obj.target/leveldb-hyper/deps/leveldb/leveldb-hyper-1.0.2/util/env.o
  CXX(target) Release/obj.target/leveldb-hyper/deps/leveldb/leveldb-hyper-1.0.2/util/histogram.o
  CXX(target) Release/obj.target/leveldb-hyper/deps/leveldb/leveldb-hyper-1.0.2/util/coding.o
  CXX(target) Release/obj.target/leveldb-hyper/deps/leveldb/leveldb-hyper-1.0.2/util/hash.o
  CXX(target) Release/obj.target/leveldb-hyper/deps/leveldb/leveldb-hyper-1.0.2/util/logging.o
  CXX(target) Release/obj.target/leveldb-hyper/deps/leveldb/leveldb-hyper-1.0.2/util/filter_policy.o
  CXX(target) Release/obj.target/leveldb-hyper/deps/leveldb/leveldb-hyper-1.0.2/util/arena.o
  CXX(target) Release/obj.target/leveldb-hyper/deps/leveldb/leveldb-hyper-1.0.2/util/cache.o
  CXX(target) Release/obj.target/leveldb-hyper/deps/leveldb/leveldb-hyper-1.0.2/util/comparator.o
  CXX(target) Release/obj.target/leveldb-hyper/deps/leveldb/leveldb-hyper-1.0.2/util/status.o
  CXX(target) Release/obj.target/leveldb-hyper/deps/leveldb/leveldb-hyper-1.0.2/util/options.o
  CXX(target) Release/obj.target/leveldb-hyper/deps/leveldb/leveldb-hyper-1.0.2/util/crc32c.o
  CXX(target) Release/obj.target/leveldb-hyper/deps/leveldb/leveldb-hyper-1.0.2/db/c.o
  CXX(target) Release/obj.target/leveldb-hyper/deps/leveldb/leveldb-hyper-1.0.2/db/log_reader.o
  CXX(target) Release/obj.target/leveldb-hyper/deps/leveldb/leveldb-hyper-1.0.2/db/repair.o
  CXX(target) Release/obj.target/leveldb-hyper/deps/leveldb/leveldb-hyper-1.0.2/db/table_cache.o
  CXX(target) Release/obj.target/leveldb-hyper/deps/leveldb/leveldb-hyper-1.0.2/db/log_writer.o
  CXX(target) Release/obj.target/leveldb-hyper/deps/leveldb/leveldb-hyper-1.0.2/db/dbformat.o
  CXX(target) Release/obj.target/leveldb-hyper/deps/leveldb/leveldb-hyper-1.0.2/db/write_batch.o
  CXX(target) Release/obj.target/leveldb-hyper/deps/leveldb/leveldb-hyper-1.0.2/db/db_impl.o
../deps/leveldb/leveldb-hyper-1.0.2/db/db_impl.cc:129:7: warning: field 'bg_fg_cv_' will be initialized after field 'allow_background_activity_' [-Wreorder]
      bg_fg_cv_(&mutex_),
      ^
1 warning generated.
  CXX(target) Release/obj.target/leveldb-hyper/deps/leveldb/leveldb-hyper-1.0.2/db/memtable.o
  CXX(target) Release/obj.target/leveldb-hyper/deps/leveldb/leveldb-hyper-1.0.2/db/leveldb_main.o
  CXX(target) Release/obj.target/leveldb-hyper/deps/leveldb/leveldb-hyper-1.0.2/db/version_edit.o
  CXX(target) Release/obj.target/leveldb-hyper/deps/leveldb/leveldb-hyper-1.0.2/db/version_set.o
../deps/leveldb/leveldb-hyper-1.0.2/db/version_set.cc:1315:1: warning: 'CompactionBoundary' defined as a struct here but previously declared as a class [-Wmismatched-tags]
struct CompactionBoundary {
^
../deps/leveldb/leveldb-hyper-1.0.2/db/version_set.h:31:1: note: did you mean struct here?
class CompactionBoundary;
^~~~~
struct
1 warning generated.
  CXX(target) Release/obj.target/leveldb-hyper/deps/leveldb/leveldb-hyper-1.0.2/db/builder.o
  CXX(target) Release/obj.target/leveldb-hyper/deps/leveldb/leveldb-hyper-1.0.2/db/filename.o
  CXX(target) Release/obj.target/leveldb-hyper/deps/leveldb/leveldb-hyper-1.0.2/db/db_iter.o
  CXX(target) Release/obj.target/leveldb-hyper/deps/leveldb/leveldb-hyper-1.0.2/db/replay_iterator.o
In file included from ../deps/leveldb/leveldb-hyper-1.0.2/db/replay_iterator.cc:5:
../deps/leveldb/leveldb-hyper-1.0.2/db/replay_iterator.h:57:24: warning: private field 'start_at_' is not used [-Wunused-private-field]
  SequenceNumber const start_at_;
                       ^
1 warning generated.
  CXX(target) Release/obj.target/leveldb-hyper/deps/leveldb/leveldb-hyper-1.0.2/port/port_posix.o
  CXX(target) Release/obj.target/leveldb-hyper/deps/leveldb/leveldb-hyper-1.0.2/table/merger.o
  CXX(target) Release/obj.target/leveldb-hyper/deps/leveldb/leveldb-hyper-1.0.2/table/filter_block.o
  CXX(target) Release/obj.target/leveldb-hyper/deps/leveldb/leveldb-hyper-1.0.2/table/block_builder.o
  CXX(target) Release/obj.target/leveldb-hyper/deps/leveldb/leveldb-hyper-1.0.2/table/iterator.o
  CXX(target) Release/obj.target/leveldb-hyper/deps/leveldb/leveldb-hyper-1.0.2/table/table_builder.o
  CXX(target) Release/obj.target/leveldb-hyper/deps/leveldb/leveldb-hyper-1.0.2/table/format.o
  CXX(target) Release/obj.target/leveldb-hyper/deps/leveldb/leveldb-hyper-1.0.2/table/table.o
  CXX(target) Release/obj.target/leveldb-hyper/deps/leveldb/leveldb-hyper-1.0.2/table/block.o
  CXX(target) Release/obj.target/leveldb-hyper/deps/leveldb/leveldb-hyper-1.0.2/table/two_level_iterator.o
  LIBTOOL-STATIC Release/leveldb-hyper.a
  CXX(target) Release/obj.target/snappy/deps/snappy/snappy-1.1.1/snappy-sinksource.o
  CXX(target) Release/obj.target/snappy/deps/snappy/snappy-1.1.1/snappy-stubs-internal.o
  CXX(target) Release/obj.target/snappy/deps/snappy/snappy-1.1.1/snappy.o
  LIBTOOL-STATIC Release/snappy.a
  CXX(target) Release/obj.target/leveldownhyper/src/batch.o
  CXX(target) Release/obj.target/leveldownhyper/src/batch_async.o
  CXX(target) Release/obj.target/leveldownhyper/src/database.o
  CXX(target) Release/obj.target/leveldownhyper/src/database_async.o
  CXX(target) Release/obj.target/leveldownhyper/src/iterator.o
  CXX(target) Release/obj.target/leveldownhyper/src/iterator_async.o
  CXX(target) Release/obj.target/leveldownhyper/src/leveldown.o
  CXX(target) Release/obj.target/leveldownhyper/src/leveldown_async.o
  SOLINK_MODULE(target) Release/leveldownhyper.node
bindings@1.2.1 node_modules/bindings

monotonic-timestamp@0.0.9 node_modules/monotonic-timestamp

fast-future@1.0.1 node_modules/fast-future

rimraf@2.2.8 node_modules/rimraf

node-uuid@1.4.3 node_modules/node-uuid

abstract-leveldown@2.2.2 node_modules/abstract-leveldown
└── xtend@4.0.0

nan@2.0.9 node_modules/nan

readfiletree@0.0.1 node_modules/readfiletree
└── async@0.1.22

du@0.1.0 node_modules/du
└── async@0.1.22

optimist@0.6.1 node_modules/optimist
├── wordwrap@0.0.3
└── minimist@0.0.10

mkfiletree@0.0.1 node_modules/mkfiletree
├── temp@0.4.0
├── async@0.1.22
└── rimraf@2.0.3 (graceful-fs@1.1.14)

slump@2.0.1 node_modules/slump
├── bs58@2.0.1
├── xtend@4.0.0
├── core-util-is@1.0.1
└── rc@0.6.0 (ini@1.3.4, strip-json-comments@0.1.3, deep-extend@0.2.11, minimist@0.0.10)

faucet@0.0.1 node_modules/faucet
├── defined@0.0.0
├── duplexer@0.1.1
├── sprintf@0.1.5
├── minimist@0.0.5
├── tape@2.3.3 (inherits@2.0.1, resumer@0.0.0, jsonify@0.0.0, deep-equal@0.1.2, through@2.3.8)
├── through2@0.2.3 (xtend@2.1.2, readable-stream@1.1.13)
└── tap-parser@0.4.3 (inherits@2.0.1, readable-stream@1.1.13)

tape@4.0.3 node_modules/tape
├── inherits@2.0.1
├── defined@0.0.0
├── resumer@0.0.0
├── deep-equal@1.0.1
├── through@2.3.8
├── object-inspect@1.0.2
└── glob@5.0.14 (path-is-absolute@1.0.0, inflight@1.0.4, once@1.3.2, minimatch@2.0.10)

node-gyp@1.0.3 node_modules/node-gyp
├── graceful-fs@3.0.8
├── osenv@0.1.3 (os-homedir@1.0.1, os-tmpdir@1.0.1)
├── nopt@3.0.4 (abbrev@1.0.7)
├── semver@4.3.6
├── mkdirp@0.5.1 (minimist@0.0.8)
├── fstream@1.0.8 (inherits@2.0.1, graceful-fs@4.1.2)
├── minimatch@1.0.0 (sigmund@1.0.1, lru-cache@2.7.0)
├── which@1.1.2 (is-absolute@0.1.7)
├── glob@4.5.3 (inherits@2.0.1, once@1.3.2, inflight@1.0.4, minimatch@2.0.10)
├── tar@1.0.3 (inherits@2.0.1, block-stream@0.0.8)
├── npmlog@1.2.1 (ansi@0.3.0, are-we-there-yet@1.0.4, gauge@1.2.2)
└── request@2.61.0 (aws-sign2@0.5.0, forever-agent@0.6.1, caseless@0.11.0, stringstream@0.0.4, tunnel-agent@0.4.1, oauth-sign@0.8.0, isstream@0.1.2, json-stringify-safe@5.0.1, extend@3.0.0, qs@4.0.0, form-data@1.0.0-rc3, combined-stream@1.0.5, mime-types@2.1.6, http-signature@0.11.0, tough-cookie@2.0.0, bl@1.0.0, hawk@3.1.0, har-validator@1.8.0)
~/Desktop/leveldown-hyper 🐈  npm test

> leveldown-hyper@1.0.0 test /Users/max/Desktop/leveldown-hyper
> tape test/*-test.js | faucet

✓ setUp common
✓ setUp db
✓ test argument-less approximateSize() throws
✓ test callback-less, 1-arg, approximateSize() throws
✓ test callback-less, 2-arg, approximateSize() throws
✓ test callback-less, 3-arg, approximateSize() throws
✓ test callback-only approximateSize() throws
✓ test 1-arg + callback approximateSize() throws
✓ test approximateSize()
✓ tearDown
✓ setUp common
✓ setUp db
✓ test callback-less, 2-arg, batch() throws
✓ test batch() with missing `value`
✓ test batch() with null `value`
✓ test batch() with missing `key`
✓ test batch() with null `key`
✓ test batch() with missing `key` and `value`
✓ test batch() with missing array
✓ test batch() with undefined array
✓ test batch() with null array
✓ test batch() with null options
✓ test batch() with empty array
✓ test simple batch()
✓ test multiple batch()
✓ test multiple batch()
✓ tearDown
✓ setUp common
✓ setUp db
✓ test batch#put() with missing `value`
✓ test batch#put() with null `value`
✓ test batch#put() with missing `key`
✓ test batch#put() with null `key`
✓ test batch#put() with missing `key` and `value`
✓ test batch#del() with missing `key`
✓ test batch#del() with null `key`
✓ test batch#del() with null `key`
✓ test batch#clear() doesn't throw
✓ test batch#write() with no callback
✓ test batch#put() after write()
✓ test batch#del() after write()
✓ test batch#clear() after write()
✓ test batch#write() after write()
✓ test basic batch
✓ tearDown
✓ test ended iterator
✓ test non-ended iterator
✓ test multiple non-ended iterators
✓ test ending iterators
✓ setUp
✓ test close()
✓ tearDown
✓ setUp common
✓ setUp db
✓ test argument-less del() throws
✓ test callback-less, 1-arg, del() throws
✓ test callback-less, 3-arg, del() throws
✓ test simple del()
✓ test del on non-existent key
✓ tearDown
✓ test argument-less destroy() throws
✓ test callback-less, 1-arg, destroy() throws
✓ test destroy non-existant directory
✓ test destroy non leveldb directory
✓ test destroy() cleans and removes leveldb-only dir
✓ test destroy() cleans and removes only leveldb parts of a dir
✓ setUp common
✓ setUp db
✓ test argument-less get() throws
✓ test callback-less, 1-arg, get() throws
✓ test callback-less, 3-arg, get() throws
✓ test simple get()
✓ test simultaniously get()
✓ tearDown
✓ setUp common
✓ setUp db
✓ test argument-less getProperty() throws
✓ test non-string getProperty() throws
✓ test invalid getProperty() returns empty string
✓ test invalid getProperty("leveldb.num-files-at-levelN") returns numbers
✓ test invalid getProperty("leveldb.stats")
✓ test invalid getProperty("leveldb.sstables")
✓ tearDown
✓ setUp common
✓ setUp db
✓ try to create an iterator with a blown stack
✓ iterate over a large iterator with a large watermark
✓ tearDown
✓ setUp common
✓ setUp db
✓ test argument-less iterator#next() throws
✓ test argument-less iterator#end() after next() throws
✓ test argument-less iterator#end() throws
✓ test twice iterator#end() callback with error
✓ test iterator#next after iterator#end() callback with error
✓ test twice iterator#next() throws
✓ test simple iterator()
✓ setUp #2
✓ test full data collection
✓ test iterator with reverse=true
✓ test iterator with start=0
✓ test iterator with start=50
✓ test iterator with start=50 and reverse=true
✓ test iterator with start being a midway key (49.5)
✓ test iterator with start being a midway key (49999)
✓ test iterator with start being a midway key and reverse=true
✓ test iterator with end=50
✓ test iterator with end being a midway key (50.5)
✓ test iterator with end being a midway key (50555)
✓ test iterator with end being a midway key and reverse=true
✓ test iterator with end=0
✓ test iterator with start=30 and end=70
✓ test iterator with start=30 and end=70 and reverse=true
✓ test iterator with limit=20
✓ test iterator with limit=20 and start=20
✓ test iterator with limit=20 and reverse=true
✓ test iterator with limit=20 and start=20 and reverse=true
✓ test iterator with limit=-1 should iterate over whole database
✓ test iterator with limit=0 should not iterate over anything
✓ test iterator with end after limit
✓ test iterator with end before limit
✓ test iterator with start after database end
✓ test iterator with start after database end and reverse=true
✓ test iterator with start and end after database and and reverse=true
✓ test iterator with start as empty buffer
✓ test iterator with end as empty buffer
✓ test iterator with start as empty string
✓ test iterator with start as null
✓ test iterator with end as empty string
✓ test iterator with end as null
✓ setUp #3
✓ iterator create snapshot correctly
✓ tearDown
✓ iterator throws if key is not a string
✓ iterator is seekable
✓ reverse seek in the middle
✓ iterator invalid seek
✓ reverse seek from invalid range
✓ test database creation no-arg throws
✓ test database creation non-string location throws
✓ test database open no-arg throws
✓ setUp common
✓ setUp db
✓ liveBackup
✓ tearDown
✓ setUp
✓ test database open no-arg throws
✓ test callback-less, 1-arg, open() throws
✓ test database open, no options
✓ test database open, options and callback
✓ test database open, close and open
✓ test database open createIfMissing:false
✓ test database open errorIfExists:true
✓ tearDown
✓ test port-libuv is being used
✓ setUp common
✓ setUp db
✓ test get() with null key causes error
✓ test del() with null key causes error
✓ test put() with null key causes error
✓ test get() with undefined key causes error
✓ test del() with undefined key causes error
✓ test put() with undefined key causes error
✓ test get() with empty String key causes error
✓ test del() with empty String key causes error
✓ test put() with empty String key causes error
✓ test get() with empty Buffer key causes error
✓ test del() with empty Buffer key causes error
✓ test put() with empty Buffer key causes error
✓ test get() with empty Array key causes error
✓ test del() with empty Array key causes error
✓ test put() with empty Array key causes error
✓ test put()/get()/del() with `false` key
✓ test put()/get()/del() with `0` key
✓ test put()/get()/del() with `NaN` key
✓ test put()/get()/del() with long String key
✓ test put()/get()/del() with Buffer key
✓ test put()/get()/del() with Array value
✓ test put()/get()/del() with `false` value
✓ test put()/get()/del() with `0` value
✓ test put()/get()/del() with `NaN` value
✓ test put()/get()/del() with `null` value
✓ test put()/get()/del() with `undefined` value
✓ test put()/get()/del() with empty String value
✓ test put()/get()/del() with empty Buffer value
✓ test put()/get()/del() with empty Array value
✓ test put()/get()/del() with long String value
✓ test put()/get()/del() with Buffer value
✓ test put()/get()/del() with Array key
✓ tearDown
✓ setUp common
✓ setUp db
✓ test argument-less put() throws
✓ test callback-less, 1-arg, put() throws
✓ test callback-less, 2-arg, put() throws
✓ test callback-less, 3-arg, put() throws
✓ test simple put()
✓ tearDown
✓ setUp common
✓ setUp db
✓ test simple iterator()
✓ setUp #2
✓ test full data collection
✓ test iterator with reverse=true
✓ test iterator with gte=0
✓ test iterator with gte=50
✓ test iterator with lte=50 and reverse=true
✓ test iterator with start being a midway key (49.5)
✓ test iterator with start being a midway key (49999)
✓ test iterator with start being a midway key and reverse=true
✓ test iterator with start being a midway key and reverse=true
✓ test iterator with start being a midway key and reverse=true
✓ test iterator with end=50
✓ test iterator with end being a midway key (50.5)
✓ test iterator with end being a midway key (50555)
✓ test iterator with end being a midway key (50555)
✓ test iterator with end being a midway key and reverse=true
✓ test iterator with gt a midway key and reverse=true
✓ test iterator with gt a midway key and reverse=true
✓ test iterator with gt 50 key and reverse=true
✓ test iterator with end=0
✓ test iterator with end<0
✓ test iterator with start=30 and end=70
✓ test iterator with start=30 and end=70
✓ test iterator with start=30 and end=70 and reverse=true
✓ test iterator with start=30 and end=70 and reverse=true
✓ test iterator with limit=20 and start=20
✓ test iterator with limit=20 and start=79 and reverse=true
✓ test iterator with end after limit
✓ test iterator with end before limit
✓ test iterator with start after database end
✓ test iterator with start after database end
✓ test iterator with start after database end and reverse=true
✓ test iterator with start and end after database and and reverse=true
✓ test iterator with lt and gt after database and and reverse=true
✓ test iterator with start as empty buffer
✓ test iterator with end as empty buffer
✓ test iterator with start as empty string
✓ test iterator with start as null
✓ test iterator with end as empty string
✓ test iterator with end as null
✓ tearDown
✓ test argument-less repair() throws
✓ test callback-less, 1-arg, repair() throws
✓ test repair non-existant directory returns error
✓ test repair() compacts
# tests 732
# pass  732
✓ ok
```

**Pull request merged**
